### ISSUE TITLE
Icons look too small

### ISSUE THREAD

**Issue by danblamar** [sergejbohlender/danieldiabolo#1]
Icons at the top of the page (logo, language...) look too small. 

I'd suggest doubling their size, for better access and layout.

**Comment by sergejbohlender** [comment]
![grafik](https://github.com/sergejbohlender/danieldiabolo/assets/71588873/82f09a45-8fc8-4be6-bdc5-7252c3caaf40)
 
- adapted icon size in latest commit, check it out
- patreon link was added

please close if we resolved the issue with this

**Comment by danblamar** [comment]
Nice change, but the report actually addressed something else:
"Icons at the top of the page (...)"

I meant these ones:
![Screenshot_20240218-004816](https://github.com/sergejbohlender/danieldiabolo/assets/160180856/ad3d0bb6-02c4-47ad-bcd5-3dbade519da0)

**Comment by sergejbohlender** [comment]
This can be done, but i need to have a deeper look in the implementation... i will do this task at last before we publish. Lets discuss this next time we call

**Comment by danblamar** [comment]
Nice. I was about to request this again, as I can't stop noticing this detail, both in phone and web version.

**Comment by sergejbohlender** [comment]
not highest, but would be nice to increase

**Comment by sergejbohlender** [comment]
icons doubled, but logo (top left) looks weird if i double it. If you want this to increase please scale these up:

![icon_black_50_50](https://github.com/user-attachments/assets/fdd95282-9ed6-4316-89a9-bbed93a4afdf)
![icon_white_50_50](https://github.com/user-attachments/assets/0ede007c-a0ce-4740-84b2-95ee4152b4ff)

**Comment by sergejbohlender** [comment]
i used 50x50 pxl -> so something like  80x80  or 100x100 would be good. Please open a new issue @danblamar
