### ISSUE TITLE
No gap in between icon and text

### ISSUE THREAD

**Issue by danblamar** [sergejbohlender/danieldiabolo#12]
It happens in both buttons :P

![FireShot Capture 005 - Daniel Diabolo - sergejbohlender github io](https://github.com/sergejbohlender/danieldiabolo/assets/160180856/0de8b9c2-f0d7-4eae-b0be-dff04ad0469c)

**Comment by sergejbohlender** [comment]
![grafik](https://github.com/user-attachments/assets/0908c738-bbeb-4496-9132-dda579474bb0)

**Comment by sergejbohlender** [comment]
@danblamar done :-)
