### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by danblamar** [sergejbohlender/danieldiabolo#14]
![Captura de pantalla 2024-02-23 200023](https://github.com/sergejbohlender/danieldiabolo/assets/160180856/34178f15-eabc-49cd-8859-adf9c208ae57)

Please list the options as follows:

English
Español
Deutsch
Français
汉语
Pусский 
اَلْعَرَبِيَّة
日本語

Always naming the language in the language itself and starting in capital letters. I'd like to eventually offer the web in all those languages :)

**Comment by sergejbohlender** [comment]
Done
