### ISSUE TITLE
Top main page layout recompositing

### ISSUE THREAD

**Issue by danblamar** [sergejbohlender/danieldiabolo#15]
- Please center Logo
- Typewritting text on top of it, also centered
- Background image lowered, to leave enough space.

![FireShot Capture 007 - Daniel Diabolo - sergejbohlender github io](https://github.com/sergejbohlender/danieldiabolo/assets/160180856/410da2ad-b62e-4335-a4f3-52e21c27badd)

Looking forward to the result! ^^

**Comment by sergejbohlender** [comment]
It was centered, and for now fine
