### ISSUE TITLE
Bright version icon change

### ISSUE THREAD

**Issue by danblamar** [sergejbohlender/danieldiabolo#17]
That icon suggests "settings" rather than "bright mode". It'd be more clear if the icon looked more like a sun. Dark mode (moon) does work fine. Please consider changing the icons into something that's more clear to the user.

![bug](https://github.com/sergejbohlender/danieldiabolo/assets/160180856/d876f68a-a694-4aea-b2e8-d2bacc9691d7)

**Comment by sergejbohlender** [comment]
This is a style of the theme creator, to expensive to change
