### ISSUE TITLE
Header have too large space

### ISSUE THREAD

**Issue by danblamar** [sergejbohlender/danieldiabolo#2]
![FireShot Capture 001 -  - sergejbohlender github io](https://github.com/sergejbohlender/danieldiabolo/assets/160180856/7d1807d1-8a3f-4ec8-9874-9dd706b9f185)

**Comment by sergejbohlender** [comment]
Please check the new version i played around with some spacing

**Comment by danblamar** [comment]
Space looks good now. Thanks! ✅
Could we make the header a 50% larger, though❓ Should I submit a separated bug for this issue?

**Comment by sergejbohlender** [comment]
Nope, its fine like that.

https://tailwindcss.com/docs/font-size

I increased the font size from ``text-2xl`` -> ``text-4xl``

**Comment by sergejbohlender** [comment]
![grafik](https://github.com/sergejbohlender/danieldiabolo/assets/71588873/e31b5b9b-31c1-43c1-bffa-6a85605c916d)
