### ISSUE TITLE
Gallery improvements

### ISSUE THREAD

**Issue by sergejbohlender** [sergejbohlender/danieldiabolo#3]
- [x] opacity of download button
- [x] background image, so its not so empty
- [x] center gallery
- [x] remove wird gallery spacings
- [x] non transparent download text

**Comment by sergejbohlender** [comment]
@danblamar  have a look on the intermediate state

**Comment by danblamar** [comment]
Button while cursor's on looks fine ✅
Button while cursor's off, would look better if only the background looked transparent, but text remain fully opaque.

It'd be nice to give a try ;)

**Comment by sergejbohlender** [comment]
Opacity increased to 80% looks good.

@danblamar i will close this issue
