### ISSUE TITLE
Social Network icons alligment

### ISSUE THREAD

**Issue by danblamar** [sergejbohlender/danieldiabolo#4]
![FireShot Capture 003 -  - sergejbohlender github io](https://github.com/sergejbohlender/danieldiabolo/assets/160180856/13fe91fd-3929-415f-b5f2-1bdca47fa2e0)

Could you center them vertically to the logo "Daniel Diabolo (...)"? and spread them evenly throughout the width of the logo? They will end up with a bit more space in between them, if you know what I mean...

**Comment by sergejbohlender** [comment]
Done

![grafik](https://github.com/sergejbohlender/danieldiabolo/assets/71588873/4de74a5b-2537-4528-a40f-233e852066af)

**Comment by danblamar** [comment]
"and spread them evenly throughout the width of the logo"

Could we make them a bit bigger and distribute them evenly so the use almost all the width of the logo?
Thanks! ^^

**Comment by sergejbohlender** [comment]
![grafik](https://github.com/sergejbohlender/danieldiabolo/assets/71588873/23c2c25e-292a-4cb3-b889-5bb9cff90ed2)

i would not make them bigger cause if we add or remove one it wil look weirder and weirder... there is no function which scale icons with width, sorry
