### ISSUE TITLE
Menu font style consistency

### ISSUE THREAD

**Issue by danblamar** [sergejbohlender/danieldiabolo#6]
![FireShot Capture 004 -  - sergejbohlender github io](https://github.com/sergejbohlender/danieldiabolo/assets/160180856/0458b37d-ae72-41e3-a590-ee1cc664d4cd)

Please copy the style and size of "about" and "Grit" to "Gallery"

**Comment by sergejbohlender** [comment]
Good find, i fixed it 
![grafik](https://github.com/sergejbohlender/danieldiabolo/assets/71588873/7c86e760-9637-4599-b981-bfe2783468b6)

**Comment by sergejbohlender** [comment]
Sorry, closed by accident
